# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  setup-dependencies:
    steps:
      - run: apt-get -y update &&
          apt-get -y install
          g++-10
          git
jobs:
  build_with_cmake:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - setup-dependencies
      - run: apt-get -y update &&
          apt-get -y install cmake
      - checkout
      - run: mkdir build
      - run: cd build && cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10
      - run: cd build && make -j 2
      - run: cd build/test && ctest -V

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "run_test"
  run_test:
    jobs:
      - build_with_cmake